### ISSUE TITLE
not asset for raspberry pi arm

### ISSUE THREAD

**Issue by mirsella** [avencera/rustywind#17]
i was installing this project https://github.com/iamcco/coc-tailwindcss and got this error with `yarn install --frozen-lockfile` : 
```
yarn install v1.13.0
[1/5] Validating package.json...
warning coc-tailwindcss@0.7.0: The engine "coc" appears to be invalid.
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
[5/5] Building fresh packages...
error /home/mirsella/.config/nvim/plugged/coc-tailwindcss/node_modules/rustywind: Command failed.
Exit code: 1
Command: node ./lib/postinstall.js
Arguments: 
Directory: /home/mirsella/.config/nvim/plugged/coc-tailwindcss/node_modules/rustywind
Output:
Finding release for v0.6.4
GET https://api.github.com/repos/avencera/rustywind/releases/tags/v0.6.4
Deleting invalid download cache
Downloading rustywind failed: Error: Asset not found with name: rustywind-v0.6.4-arm-unknown-linux-gnueabihf.tar.gz
    at getAssetFromGithubApi (/home/mirsella/.config/nvim/plugged/coc-tailwindcss/node_modules/rustywind/lib/download.js:168:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

yeah there no asset with the name `rustywind-v0.6.4-arm-unknown-linux-gnueabihf.tar.gz` in the release.
but there is `rustywind-v0.6.6-arm-unknown-linux-gnueabi.tar.gz` which probably work ?
`uname -a` : 
`Linux rpi 5.4.51-v8+ #1333 SMP PREEMPT Mon Aug 10 16:58:35 BST 2020 aarch64 GNU/Linux`

it's little to work with but i don't know what i can send to help more. so don't hesitate to ask me questions

**Comment by praveenperera** [comment]
Hey best thing to do would be to go to coc-tailwindcss or headwind repo and bump the rustywind dependency go 0.6.6.

**Comment by mirsella** [comment]
so it use 0.6.6 ? this release still don't have `rustywind-v0.6.4-arm-unknown-linux-gnueabihf.tar.gz` which is tried to but downloaded. 

i opened the issue on rustywind because i thought the download was managed by rusywind. is it ? if the filename which doesn't exist is not provided by rustywind i'll close this issue, and i'll try to search where it come from in the coc-tailwindcss repo.

thanks

**Comment by praveenperera** [comment]
coc-tailwind uses rustywind 0.6.5 which had the issue because it wasn’t building for that arm platform. 

This was fixed in rustywind 0.6.6 if coc-tailwind updates to that version you won’t have this issue. As it will download the correct binary.

**Comment by mirsella** [comment]
i've forked it [here](https://github.com/mirsella/coc-tailwindcss) to try to update the version to 0.6.6. 
`yarn list | grep rustywind` show `rustywind@0.6.6` so it's updated, but i still get this error with`yarn install --frozen-lockfile` : 

```
yarn install v1.13.0
[1/5] Validating package.json...
warning coc-tailwindcss@0.7.0: The engine "coc" appears to be invalid.
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
[5/5] Building fresh packages...
error /home/mirsella/.config/nvim/plugged/coc-tailwindcss/node_modules/rustywind: Command failed.
Exit code: 1
Command: node ./lib/postinstall.js
Arguments: 
Directory: /home/mirsella/.config/nvim/plugged/coc-tailwindcss/node_modules/rustywind
Output:
Finding release for v0.6.6 

GET https://api.github.com/repos/avencera/rustywind/releases/tags/v0.6.6
Deleting invalid download cache
Downloading rustywind failed: Error: Asset not found with name: rustywind-v0.6.6-arm-unknown-linux-gnueabihf.tar.gz
    at getAssetFromGithubApi (/home/mirsella/.config/nvim/plugged/coc-tailwindcss/node_modules/rustywind/lib/download.js:165:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by mirsella** [comment]
i've forked it [here](https://github.com/mirsella/coc-tailwindcss) to try to update the version to 0.6.6. 
`yarn list | grep rustywind` show `rustywind@0.6.6` so it's updated, but i still get this error with`yarn install --frozen-lockfile` : 

```
yarn install v1.13.0
[1/5] Validating package.json...
warning coc-tailwindcss@0.7.0: The engine "coc" appears to be invalid.
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
[5/5] Building fresh packages...
error /home/mirsella/.config/nvim/plugged/coc-tailwindcss/node_modules/rustywind: Command failed.
Exit code: 1
Command: node ./lib/postinstall.js
Arguments: 
Directory: /home/mirsella/.config/nvim/plugged/coc-tailwindcss/node_modules/rustywind
Output:
Finding release for v0.6.6 

GET https://api.github.com/repos/avencera/rustywind/releases/tags/v0.6.6
Deleting invalid download cache
Downloading rustywind failed: Error: Asset not found with name: rustywind-v0.6.6-arm-unknown-linux-gnueabihf.tar.gz
    at getAssetFromGithubApi (/home/mirsella/.config/nvim/plugged/coc-tailwindcss/node_modules/rustywind/lib/download.js:165:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by praveenperera** [comment]
Try nkw

**Comment by mirsella** [comment]
It work !

thanks a lot.

what did you do ?

**Comment by praveenperera** [comment]
Great sorry it was a typo in my assets. I’m not at a computer so I didn’t see it. Thanks for creating this issue.
